import { lists } from "$lib/global.svelte";
import type { ListObj } from "$lib/types";
import { compressToEncodedURIComponent, decompressFromEncodedURIComponent } from "lz-string";
import { getRandom } from "./helpers";

export function createListId() {
    return `${Date.now()}-${getRandom().split("-")[0]}`
}

export function createList(name: string) {
    const newList: ListObj = {
        id: createListId(),
        name,
        items: []
    };
    lists.push(newList);
}

export function getListById(listId: string) {
    return lists.find(list => list.id === listId);
}

export function deleteList(list: ListObj) {
    lists.splice(lists.indexOf(list), 1);
}

export function updateListName(list: ListObj, newName: string) {
    list.name = newName;
}

export function getListItem(list: ListObj, itemNumber: string) {
    const item = list.items.find(i => i.id === itemNumber);
    if (item) return item
    return null
}

export function updateQuantity(list: ListObj, itemNumber: string, newQuantity: number) {
    const item = list.items.find(i => i.id === itemNumber);
    if (item) item.q = newQuantity;
}

export function getItemQuantity(list: ListObj, itemNumber: string) {
    return list.items.find(i => i.id === itemNumber)?.q || 0;
}

// Retrieves the timestamp from the list's ID and returns it as a Date object. If the list is null or the timestamp is invalid, it returns null.
export function getListTimestamp(list: ListObj) {
    const timestamp = list ? parseInt(list.id.split("-")[0]) : null;
    return timestamp ? new Date(timestamp) : null;
}

// Checks if a specific item number exists in the given list. Returns true if the item is found, otherwise false.
export function isInList(list: ListObj, itemNumber: string) {
    return list ? list.items.some(item => item.id === itemNumber) : false;
}

// Gets all lists that contain the specified item number. Returns an array of list IDs.
export function inLists(itemNumber: string) {
    return lists.filter(list => list.items.some(item => item.id === itemNumber)).map(list => list.id);
}

export function addToList(list: ListObj, itemNumber: string) {
    if (list.items.some(item => item.id === itemNumber)) {
        updateQuantity(list, itemNumber, (list.items.find(i => i.id === itemNumber)?.q || 0) + 1);
    } else {
        list.items.push({ id: itemNumber, q: 1 });
    }
}

export function removeFromList(list: ListObj, itemNumber: string) {
    if (list.items.some(item => item.id === itemNumber)) {
        const item = list.items.find(i => i.id === itemNumber);
        if (item) item.q -= 1;
    }
    list.items = list.items.filter(item => item.id !== itemNumber);
}

/**
 * Converts a list object to a URI-encoded string using LZ-string compression. This function is useful for sharing or storing list data in a compact format.
 * @param list The list object to be converted into a URI-encoded string. The list should conform to the ListObj type, containing an id, name, and an array of items.
 * @returns A URI-encoded string representing the compressed list object. This string can be used in URLs or stored for later retrieval.
 */

export function listToURI(list: ListObj) {
    return compressToEncodedURIComponent(JSON.stringify(list));
}

/**
 * Converts a URI-encoded string back into a list object. This function decompresses the string and parses it into a ListObj, allowing for easy retrieval of list data from a compact format.
 * @param uri The URI-encoded string representing the compressed list object. This string should have been generated by the listToURI function and is expected to be in a valid compressed format.
 * @returns The decompressed and parsed list object of type ListObj. If the URI cannot be decompressed or parsed, the function returns null, indicating that the input was invalid or corrupted.
 */

export function URIToList(uri: string) {
    try {
        const decoded = JSON.parse(decompressFromEncodedURIComponent(uri));
        return Array.isArray(decoded.items) ? decoded : null;
    } catch(e) {
        return null
    }
}

/**
 * Validates a list object represented by a URI. The function checks if the URI can be decompressed and parsed into a valid list object with the required fields and valid item structures.
 * @param uri The URI string representing the list object, which is expected to be compressed and encoded.
 * @returns A boolean indicating whether the list object is valid (true) or not (false).
 */
export function validateList(uri: string) {
    const list = URIToList(uri);
    if (!list) return false;

    // Check if all required fields are present
    const requiredFields = ['id', 'name', 'items'];
    for (const field of requiredFields) {
        if (!(field in list)) return false;
    }

    // Check if items are valid
    if (!Array.isArray(list.items)) return false;
    for (const item of list.items) {
        if (typeof item.id !== 'string' || typeof item.q !== 'number') return false;
    }

    return true;
}

export function saveList(list: ListObj) {
    const copy = { ...list, id: createListId() }
    lists.push(copy);
    return copy
}
