name: Build and move files to gh-pages branch

on:
  push:
    branches: [ 'main' ]

jobs:
  build_site:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun i

      - name: build
        env:
          BASE_PATH: ''
        run: |
          bun run build

      
      - name: Delete all files except build directory
        run: |
          shopt -s extglob
          rm -rf !(build)

      - name: Move built files to root
        run: |
          mv build/* .
          rm -rf build

      - name: Copy 404.html to index.html
        run: |
          cp 404.html index.html

      - name: Create CNAME file
        run: echo "alkometriikka.fi" > CNAME

      - name: Push build to gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages [skip ci]" || echo "No changes to commit"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
      
      